KKirsz\Photos\Domain\Photo\Photo:    
    type: entity
    repositoryClass: KKirsz\Photos\Infrastructure\Persistence\DoctrinePhotoRepository
    table: photo
    id: 
        id:
            name: id
            type: integer
            options:
                unsigned: true
            generator:
                strategy: AUTO
    embedded:
        photoId:            
            class: KKirsz\Photos\Domain\Photo\PhotoId            
            columnPrefix: false     
    manyToOne:
        addedBy:
            targetEntity: KKirsz\Photos\Domain\Photo\User
            joinColumn:
                name: added_by
                referencedColumnName: id
                nullable: false
    manyToMany:
        tags:
            targetEntity: KKirsz\Photos\Domain\Photo\Tag
            joinTable:
                name: photo_tag
                joinColumns:
                    photo_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    tag_id:
                        referencedColumnName: id
            indexBy: tagId.uuid
    uniqueConstraints:
        UNIQ_uuid:
            columns: [uuid]            
            